services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server
    environment:
      - LLAMA_ARG_MODEL=/models/LFM2.5-1.2B-Instruct-Q4_K_M.gguf
    ports:
      - "8010:8080"
    volumes:
      - ./.models:/models
    devices:
      - /dev/dri:/dev/dri
